# Generated by Django 5.1.1 on 2024-11-13 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profesional_rut_remove_usuario_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='user',
        ),
        migrations.AddField(
            model_name='profesional',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
